#!/bin/mksh
# -*- mode: sh -*-
# © Thorsten Glaser, Qvest Digital Ⓕ MirBSD

export LC_ALL=C
unset LANGUAGE

function die {
	print -ru2 "E: $*"
	exit 1
}

(( USER_ID == 0 )) || die need root
set -exo pipefail

umask 022
cd "$(dirname "$0")"
rm -rf base base.tgz
mkdir base
chown 0:0 base
chmod 00700 base
cd base

mkdir dev dev/pts dev/shm etc mnt proc run sys tmp
chown 0:0 dev dev/pts dev/shm etc mnt proc run sys tmp
chmod 00755 dev dev/pts dev/shm etc mnt proc run sys
chmod 01777 tmp
mknod dev/null		c 1 3
mknod dev/zero		c 1 5
mknod dev/random	c 1 8
mknod dev/urandom	c 1 9
mknod dev/tty		c 5 0
mknod dev/console	c 5 1
mknod dev/ptmx		c 5 2
chown 0:0 dev/null dev/zero dev/random dev/urandom
chown 0:5 dev/tty dev/console dev/ptmx
chmod 0666 dev/null dev/zero dev/random dev/urandom dev/tty dev/ptmx
chmod 0620 dev/console
ln -s /proc/self/fd dev/fd
ln -s fd/0 dev/stdin
ln -s fd/1 dev/stdout
ln -s fd/2 dev/stderr
ln -s /proc/mounts etc/mtab
cat >etc/passwd <<\EOF
root:x:0:0:root:/:/bin/sh
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
EOF
cat >etc/group <<\EOF
root:x:0:
tty:x:5:
nogroup:x:65534:
EOF
# /dev/shm is mounted by default by the runtime, apparently
# cf. https://raw.githubusercontent.com/moby/moby/master/oci/defaults.go
# /run ought to be (and /tmp should be) a tmpfs, but to get that
# we need a starter that mounts them, so the overlayfs has to suffice
ln -s /dev/shm run/shm

find * -print0 | sort -z | \
    paxcpio -o0C512 -Hustar -M0x85 | \
    gzip -n9 >../base.tgz
cd ..
rm -r base
exit 0
